### ISSUE TITLE
How do I localize the string of header and row titles?

### ISSUE THREAD

**Issue by rlam3** [venmo/Static#102]
How do I localize the string of header and row titles? 
I keep getting the following error...

![screen shot 2017-04-26 at 2 02 54 pm](https://cloud.githubusercontent.com/assets/1154044/25451831/1508e6aa-2a89-11e7-945c-bf0b947cff92.png)

**Comment by rlam3** [comment]
Found what I was looking for in older issues.

https://github.com/venmo/Static/issues/98

However why do we have to do a ".title()" for the header but not the rows?

**Comment by eliperkins** [comment]
@rlam3: This is because `Header` is an enum of either a `.view` or a `.title`: https://github.com/venmo/Static/blob/321e997b9c2edc5d38aa0b007f2861ba457f13ed/Static/Section.swift#L11
