### ISSUE TITLE
Blank section headers are displayed under iOS 11

### ISSUE THREAD

**Issue by nealyoung** [venmo/Static#105]
It looks like blank section headers/footers are being shown on devices running iOS 11 (as of beta 2) when a `Section` is initialized with `nil` as a header/footer extremity.

The below screenshots were taken with the example project after changing the value of the `header` parameter of the first section to `nil`.

| iOS 10 | iOS 11 |
| ------ | ------ |
| <img width="432" alt="screen shot 2017-06-29 at 4 10 41 pm" src="https://user-images.githubusercontent.com/1132493/27714667-3d092f58-5ce7-11e7-9f7a-e82b8dbae557.png"> | <img width="432" alt="screen shot 2017-06-29 at 4 10 39 pm" src="https://user-images.githubusercontent.com/1132493/27714671-4495a940-5ce7-11e7-93a9-0ff99b747a59.png"> |

**Comment by eliperkins** [comment]
Interesting! Is this a change with iOS 11 itself? That is, even without this library, this is the functionality you'd get when returning nil from `titleForHeaderInSection`?

If so, I'm wondering if this is something we should explicitly handle in this library, if this is still the functionality UIKit would provide anyway.

**Comment by nealyoung** [comment]
I just did a quick test with a simple table view/data source/delegate and it doesn't appear that the `titleForHeaderInSection` behavior has changed in iOS 11. When I return `nil`, no header is displayed, and returning a string shows the default header with the provided title.

**Comment by nealyoung** [comment]
Potentially relevant snippet from the iOS beta release notes:

>Table views now use estimated heights by default, which also means that cells and section header/footer views now self-size by default. The default value of the estimatedRowHeight, estimatedSectionHeaderHeight, and estimatedSectionFooterHeight properties is now UITableViewAutomaticDimension, which means the table view selects an estimated height to use. You should still provide a more accurate estimate for each property if possible, which is your best guess of the average value of the actual heights. If you have existing table view code that behaves differently when you build your app with the iOS 11 SDK, and you don’t want to adopt self-sizing, you can restore the previous behavior by disabling estimated heights by setting a value of zero for each estimated height property. (30197915)

I'm not sure if it's the best solution, but as a workaround, setting the estimated heights has restored the correct behavior on iOS 11 and doesn't appear to cause any problems on iOS 10:

```swift
    private func updateTableView() {
        guard let tableView = tableView else { return }
        tableView.dataSource = self
        tableView.delegate = self

        tableView.estimatedRowHeight = 0
        tableView.estimatedSectionHeaderHeight = 0
        tableView.estimatedSectionFooterHeight = 0

        refresh()
    }
```

**Comment by eliperkins** [comment]
Ah, I wonder if we should turn this on in `Static.TableViewController` then.

@soffes @hyperspacemark @venmo/ios and crew, have y'all ran into a similar issue with this on iOS 11 as well?

**Comment by soffes** [comment]
Seems reasonable 🤷🏻‍♂️ I feel bad changing defaults, but the whole point of Static is you don't have to think about table view details so maybe its good?

**Comment by hyperspacemark** [comment]
This is our bug. In the `tableView(_: heightForXXXInSection:)` methods, we're providing the height of the optional extremity and nil coalescing to `UITableViewAutomaticDimension`. That was probably a bad choice; I just confirmed that nil-coalescing to 0 works as intended.

@nealyoung Would you mind submitting a PR to that effect?

See:
* https://github.com/venmo/Static/blob/master/Static/DataSource.swift#L207
* https://github.com/venmo/Static/blob/master/Static/DataSource.swift#L219

**Comment by nealyoung** [comment]
@hyperspacemark Thanks for the help! I'll submit a PR tonight.

**Comment by eliperkins** [comment]
Related from today's [iOS 11b3 Release Notes](https://download.developer.apple.com/Documentation/Beta_Release_Notes_Jul_10_2017/iOS_11_beta_3_Release_Notes.pdf)

>• Table views in Interface Builder documents compiled with Xcode 9.0 may have fixed
heights for rows, section headers, and section footers, and may not self-size by default.
(32188814)
Workaround: Set the table view `rowHeight`, `sectionHeaderHeight`, or
`sectionFooterHeight` to `UITableViewAutomaticDimension` after the table view
has been instantiated.

**Comment by nealyoung** [comment]
@hyperspacemark It looks like nil-coalescing to 0 doesn't work with a `title` extremity (`viewHeight` is nil without a custom view, so the method returns 0), but something like this fixes the issue and works properly under iOS 10 and 11:

```swift
        if let sectionHeader = section(at: sectionIndex)?.header {
            return sectionHeader.viewHeight ?? UITableViewAutomaticDimension
        } else {
            return 0
        }
```

Let me know if that works for you. If so, I'll submit a PR with the changes.

**Comment by eliperkins** [comment]
@nealyoung What do you think about updating the `viewHeight` computed var to switch on `.title` and `.view`, and only return the view's height on custom headers?

Additionally, we could return `UITableViewAutomaticDimension` for `.title` there as well and make it a non-optional property.

**Comment by nealyoung** [comment]
@eliperkins Just submitted a PR with your suggestions!
