### ISSUE TITLE
Seperate table initializer and view handling

### ISSUE THREAD

**Issue by teawithfruit** [venmo/Static#127]
Hello,
Is it possible to split the initializer logic and the view handler in different classes?

Right now, I'm trying something like this to initialize the table
```swift
class SomeViewController: TableViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        dataSource.sections = [
            Section(rows: [
                Row(text: "Hi")
            ])
        ]
    }
}
```

And both of the following to add the table to the screen.
```swift
let table: UIViewController = SomeViewController()  
view.addSubview(table.view)
```
```swift
let table: TableViewController = SomeViewController()  
view.addSubview(table.tableView)
```
There is no error, but there is also nothing been added to the screen.
What do I have to do, to split the table initializer from the view handler?

Thanks

**Comment by eliperkins** [comment]
(You can use `DataSource` directly with any table view](https://github.com/venmo/Static#working-with-the-data-source). Using `TableViewController` is not a strict requirement, but rather just a nicer API.

When using `TableViewController` as a child view controller, make sure that you constrain `tableView.view` using autolayout or give it a proper frame. I'd recommend looking at the view debugger to get more information.
