### ISSUE TITLE
Publish 4.0.0 with CocoaPods

### ISSUE THREAD

**Issue by mliberatore** [venmo/Static#148]
The latest release available via CocoaPods is `3.0.2` (see https://cocoapods.org/pods/Static). Would it be possible to push the latest podspec to the specs repo so that `4.0.0` could be installed via CocoaPods with a specific version specified?

**Comment by digimarktech** [comment]
> The latest release available via CocoaPods is `3.0.2` (see https://cocoapods.org/pods/Static). Would it be possible to push the latest podspec to the specs repo so that `4.0.0` could be installed via CocoaPods with a specific version specified?

While the 4.0.0 version isn't available via cocoapods at the moment, I was able to use the following line to specify the 4.0.0 version: `pod 'Static', git: 'https://github.com/venmo/Static', tag: 'v4.0.0'`

**Comment by dmiluski** [comment]
Updated:
https://cocoapods.org/pods/Static

**Comment by mliberatore** [comment]
Thank you, @dmiluski!
