### ISSUE TITLE
Logo for repo

### ISSUE THREAD

**Issue by cassidoo** [venmo/Static#22]
![static](https://cloud.githubusercontent.com/assets/1454517/8715434/f5fa23c6-2b4f-11e5-9d4e-dcfed9d9a645.png)

I thought it might be cool to have more of our repos have logos (the way Slather and Synx do), so I tried my hand at it.  Bueno?  Suggestions?

**Comment by soffes** [comment]
Super cool!

**Comment by ayanonagon** [comment]
Whoa this is super cool @cassidoo! :100:

**Comment by ayanonagon** [comment]
Thanks for the PR @cassidoo! :blue_heart:
