### ISSUE TITLE
Xcode beta 6

### ISSUE THREAD

**Issue by paulbruneau** [venmo/Static#34]
My teammate tells me there are beta 6 issues. I'll look at them unless you folks are already working on them. Any news? Thank you.

**Comment by ayanonagon** [comment]
Can you elaborate on the Beta 6 issues? We’re using beta 6 as well and have not seen any issues so far.

**Comment by paulbruneau** [comment]
Thanks, I have looked and I think this might be the only one, pretty straightforward fix:

<img width="627" alt="screen shot 2015-08-27 at 10 55 28 am" src="https://cloud.githubusercontent.com/assets/978400/9523904/2cc4bcc4-4caa-11e5-9a41-ccba57c09228.png">
