### ISSUE TITLE
How to implement a custom cell with .xib and variable height?

### ISSUE THREAD

**Issue by dillidon** [venmo/Static#43]

**Comment by Valpertui** [comment]
See https://github.com/venmo/Static/pull/45

**Comment by dillidon** [comment]
thanks a lot)

**Comment by dillidon** [comment]
ok, how to implement function or to change variables inside custom cell such as custom selection? 
could you add switch as accessory with selection, which can add or remove sections and rows?

**Comment by eliperkins** [comment]
I'm going to close this in favor of #45
