### ISSUE TITLE
fatalError("init(coder:) has not been implemented")

### ISSUE THREAD

**Issue by gizcloud** [venmo/Static#49]
I installed Static by cocoapods. when I try to run it ,it crashed in this line:
fatalError("init(coder:) has not been implemented")

I don't know why.

**Comment by eliperkins** [comment]
Are you creating a Static view controller with Interface Builder? Static does not currently support Interface Builder, which calls into `init(coder:)`.

**Comment by gizcloud** [comment]
yes.
