### ISSUE TITLE
TableViewController clear selection bug

### ISSUE THREAD

**Issue by calebd** [venmo/Static#50]
`TableViewController` exhibits the same problem that `UITableViewController` does when attempting to clear selection during an interactive "go back" gesture. It just doesn't clear sometimes. It's even stranger if you cancel the gesture. I used this logic before switching to static to resolve the issue: [gist](https://gist.github.com/calebd/e6246d416b12c52c7fa5). It would be cool if this were integrated into Static.

**Comment by eliperkins** [comment]
Ah, I definitely agree that `UITableViewController` has it's quirks. I'm a bit wary of making `TableViewController` do _too_ much. I believe the only reason that Static recreates a `TableViewController` was dues to some bizarre Swift `init()` quirks (see #30). 

I'm wondering if `TableViewController` should be built by just adding a child view controller of a `UITableViewController`, but I digress...

That said, if we feel passionately that fixing `UITableViewController`'s bugs is within the scope of what Static's `TableViewController`, I would definitely be open to a PR adding this!

**Comment by soffes** [comment]
I agree with @eliperkins. I think using the system defaults is best, but fixing a common bug that most would workaround seems worth it to me.

(Related to #62)
