### ISSUE TITLE
How to implement function or to change variables inside custom cell such as custom selection?  

### ISSUE THREAD

**Issue by dillidon** [venmo/Static#51]

**Comment by eliperkins** [comment]
Static is meant primarily for implementing _static_ table view cells. Changing properties of a table view cell, done The Static Way™, should be done by creating a new `Row` to create the new cell. You can supply `context` to the cell via the initializer for a `Row`, and then in the custom cell class, implementing `configure(_:)` and using the `context` property to setup your cell should get you most of the way there.
