### ISSUE TITLE
Could you add switch as accessory with selection, which can add or remove sections and rows?

### ISSUE THREAD

**Issue by dillidon** [venmo/Static#52]

**Comment by eliperkins** [comment]
Again, similar to as you asked in #51, changes in the table view's state should be driven by setting the properties of a `DataSource`, such as creating new `Row` objects. In this case, things get a bit complex with the switch as the accessory and reacting to it's changes, but in the end, whatever function that runs when the switch is toggled should set the `sections` on your `DataSource` to change sections, or `rows` on your `Section` to add or remove rows.
