### ISSUE TITLE
Question:How to override func configure(row row: Row) in protocol CellType

### ISSUE THREAD

**Issue by flexih** [venmo/Static#68]

**Comment by flexih** [comment]
@eliperkins

**Comment by eliperkins** [comment]
The goal is not to _override_ `configure(_:)`, actually, but rather to have your class _implement_ it. You can see an example of implementing `configure(_:)` here: https://github.com/venmo/Static/blob/0b89f36f33fdd4ae0593830a01e69f5452d9cba3/Example/CustomTableViewCell.swift

**Comment by flexih** [comment]
Found the reason, if SomeCellClass inherits Value1Cell, it's impossible to "override" configure(:) in CellType. @eliperkins
