### ISSUE TITLE
Please add to the CocoaPods specs repository

### ISSUE THREAD

**Issue by irace** [venmo/Static#76]
Why is Static not versioned in the CocoaPods specs repository? This makes it impossible for other pods to depend on it.

**Comment by eliperkins** [comment]
Whoops! Not sure how that one hasn't happened yet. This library was put together before Cocoapods was accepting Swift-based pods to Trunk.

I just pushed, it should be there now! https://github.com/CocoaPods/Specs/commit/5e9f1a362c3332dbdb84ce5a492d3d41f42aaecf

**Comment by irace** [comment]
Thanks!
