### ISSUE TITLE
Podspec out of date with latest version

### ISSUE THREAD

**Issue by chrismanderson** [venmo/Static#85]
While the latest tagged version is 1.1.1, the latest version referenced in the podspec is only 1.0.0.

**Comment by hyperspacemark** [comment]
Good catch. We don't use CocoaPods internally so we often forget this. Feel free to submit a PR and I'll push it to the CP trunk.

**Comment by chrismanderson** [comment]
PR submitted!

**Comment by hyperspacemark** [comment]
Pushed to trunk.
