### ISSUE TITLE
NSLocalizedString support

### ISSUE THREAD

**Issue by Shadester** [venmo/Static#98]
How do you do localization for this?

**Comment by eliperkins** [comment]
Localized stings can be passed into any initializer that accepts strings as arguments, such as `Section.init` and `Row.init`. For example: 

```swift
let section = Section(NSLocalizedString("FIRST_SECTION_TITLE", comment: "First Section"), rows: [
    Row(NSLocalizedString("FIRST_ROW_TITLE", comment: "First Row")
])
```

**Comment by Shadester** [comment]
It gives errors on that:

![capturfiles](https://cloud.githubusercontent.com/assets/869974/22656681/ed6eb288-ec48-11e6-96de-d85f22d6216c.png)

**Comment by eliperkins** [comment]
Ah, my apologies. I was typing from memory. This should work just fine:

```swift
let section = Section(header: .title(NSLocalizedString("FIRST_SECTION_TITLE", comment: "First Section")), rows: [
    Row(text: NSLocalizedString("FIRST_ROW_TITLE", comment: "First Row"))
])
```
