### ISSUE TITLE
How do I center the text inside of the cell/row?

### ISSUE THREAD

**Issue by rlam3** [venmo/Static#99]
How do I center the text inside of the cell/row?

**Comment by eliperkins** [comment]
This can be done using the `.default` `UITableViewCellStyle` (https://developer.apple.com/reference/uikit/uitableviewcellstyle) if you only want vertical alignment.

To center the label horizontally, you can create a custom `UITableViewCell`, like is done in the example: https://github.com/venmo/Static/blob/321e997b9c2edc5d38aa0b007f2861ba457f13ed/Example/CustomTableViewCell.swift
